/**:
  ros__parameters:
    object_detection:
      # This absolute path bridges the two workspaces perfectly!
      detection_model: 'CUSTOM_YOLOLIKE_BOX_OBJECTS'
      #custom_onnx_file: '/home/cupcake/Prequal/src/ros_controls/ros_controls/best.onnx'
      custom_onnx_file: '/home/cupcake/Desktop/prequal-task/src/ros_controls/models/Pq_gate.onnx'
      custom_onnx_input_size: 608 
      
      custom_class_count: 1 

      class_0:
        label: 'gate'
        model_class_id: 0
        enabled: true
        confidence_threshold: 30.0
        is_grounded: false
        is_static: true
